version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    assignees:
      - vladyslavvolkov

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
    assignees:
      - vladyslavvolkov
