name: Docker workflows
on: push
env:
  API_KEY: ${{ secrets.apiKey }}
  API_TOKEN: ${{ secrets.apiToken }}
  API_USER_CLAIM_ID: username
  API_USER_CLAIM_ROLES: roles
  APP_NAME: hiberbee-gateway
  APP_VERSION: 1.0.0
  ENGINE_API_KEY: ${{ secrets.apolloApiKey }}
  ENGINE_SCHEMA_TAG: ${{ github.branch }}
  GITHUB_TOKEN: ${{ secrets.github }}
  JWT_ALGORITHM: HS512
  NODE_ENV: production
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/container-action@master
        with:
          image: template-typescript-graphql
